### ISSUE TITLE
Implementation of Annotorius and angular JS in ConedaKor database 

### ISSUE THREAD

**Issue by anne-cecile** [igorlino/angular-annotorious#2] opened 2015-07-09 15:20 UTC
Hi Igorlino ! 

Thank you so much for your great job, I really appreciate the quality of your code. It really helps me with my issue : I'd like to integrate Annotorius in Conedakor database ([https://github.com/coneda/kor]). The new version of the database will use angular JS. I try to use Annotorius in my view, but it doesn't work. I can see the icon "click and drag to annotate" top left on my image but I can't annotate, what's frustrating ... I try to integrate your library angular-annotorius and put the name of the directive in the img element but it also doesn't work. 

My angular js directive kor-anno : 

```
kor.directive "korAnno", [
  "$http",
  (http) ->
    directive = {
      link: (scope, element, attrs) ->
        myImage = jQuery(element)
        myImage.bind 'load', ->   
          console.log('loaded')
          scope.$apply -> 
            anno.makeAnnotatable(element[0])
        #myImage.on "mouseover", (event) ->
        #  #event.preventDefault()
        #  console.log "qsdf"
        if myImage 
          console.log("img picked up")
          console.log(myImage)
        window.e = element    
      priority: 100
    }
]
```

the code about the view :

```
  <div ng-show="checked">
    <div class="section_panel">
        <div class="header">
         <a href="#" ng-click="toggle_checked($event)" style="font-weight:bold">Quit annotation</a><br/>
         <p>Nam vitae bibendum nunc. Pellentesque a aliquet orci, eget dictum ligula. Donec non molestie arcu. Morbi dignissim, libero non semper lobortis, neque elit fermentum risus, ac congue nibh sem quis ex. Fusce in fermentum orci, non pellentesque urna. In ac mauris et urna aliquet tincidunt. </p>
            <!-- link to medium -->
              <img alt="Image" class="-annotationlayer kor_medium" ng-src="{{entity.medium.url | image_size:'screen'}}" style="width:100%" kor-anno="myImage">
          <div class="title" ng-bind="entity.display_name" ></div>
        </div>
      </div>
  </div>
```

I presume it's not a timing issue, images are loaded before the directive. I put priority level 100 for kor-anno and ng-src is level 99. I also check the networks tab and Annotorious has loaded. I'm getting lost ...

**Comment by igorlino** [comment] 2015-07-09 19:46
Hi Anne-Cecile,

I will try update the demo page a bit better.

Meanwhile there is an explanation at:
http://stackoverflow.com/questions/30720798/how-to-use-annotorious-with-angular/30720811#30720811

(feel free to vote and/or comment on it)

**Comment by igorlino** [comment] 2015-07-09 19:48
BTW I don't think you need to implement your own annotorious directive.
I will try put an example how to integrate with local cache. perhaps that gives a further hint.

**Comment by anne-cecile** [comment] 2015-07-10 12:32
Hi ! Thank you for your help, Igorlino. It's actually a problem with the loading of images. I put a timeout function with 2500 ms on makeAnnotatable in my directive and it works. I guess the issue concerns the image loading which takes 2 seconds :)

**Comment by igorlino** [comment] 2015-07-10 19:14
I see, well still its a kind of dynamic content issue. Either you use jquery hack ready to wait for loading the page/resources/images. Or you could use something like http://stackoverflow.com/questions/18627609/angularjs-resolve-to-wait-until-external-images-have-loaded
that tells you when images finish loading. At least thats the direction I would go if I had to do the same you need to do.

Also, you may want NOT  to use directly the "anno" object. Instead you could use the "annotoriousService" angular service from the angular-annotorious library.

**Comment by igorlino** [comment] 2015-07-16 07:43
Ok, seems its not a bug in the angular library code base. I'm closing this issue. Thanks for your showing your example usage.

**Closed as completed by igorlino** 2015-07-16 07:43 UTC
